// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPeer(arg1, arg2) {
  return window['go']['controller']['Controller']['ConnectToPeer'](arg1, arg2);
}

export function ContinueAllDownloads() {
  return window['go']['controller']['Controller']['ContinueAllDownloads']();
}

export function ContinueDownload(arg1) {
  return window['go']['controller']['Controller']['ContinueDownload'](arg1);
}

export function CreateDownload(arg1) {
  return window['go']['controller']['Controller']['CreateDownload'](arg1);
}

export function DeployLibraryInstance(arg1) {
  return window['go']['controller']['Controller']['DeployLibraryInstance'](arg1);
}

export function GetDownloads() {
  return window['go']['controller']['Controller']['GetDownloads']();
}

export function GetGameFromStoreByRootHash(arg1) {
  return window['go']['controller']['Controller']['GetGameFromStoreByRootHash'](arg1);
}

export function GetOwnedGames() {
  return window['go']['controller']['Controller']['GetOwnedGames']();
}

export function GetPeerInformation() {
  return window['go']['controller']['Controller']['GetPeerInformation']();
}

export function GetStoreGames() {
  return window['go']['controller']['Controller']['GetStoreGames']();
}

export function IsDownloading(arg1) {
  return window['go']['controller']['Controller']['IsDownloading'](arg1);
}

export function JoinLibraryInstance(arg1, arg2) {
  return window['go']['controller']['Controller']['JoinLibraryInstance'](arg1, arg2);
}

export function PurchaseGame(arg1) {
  return window['go']['controller']['Controller']['PurchaseGame'](arg1);
}

export function StartDownloadListener() {
  return window['go']['controller']['Controller']['StartDownloadListener']();
}

export function UploadGame(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['controller']['Controller']['UploadGame'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
