games:
    installfolder: ./test/data/tmp
meta:
    directory: ./test/data/.toolkit
    hashes:
        directory: ./test/data/.toolkit/hashes
        shardsize: 16384
        workercount: 5
    log: stdout
    threadpoolsize: 10
user:
    info:
        domain: t02smith.com
        name: tom
