// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {map[string]main} from '../models';
import {main} from '../models';

export function CreateDownload(arg1:string):Promise<boolean>;

export function DeployLibraryInstance(arg1:string):Promise<string>;

export function GetAllGames():Promise<void>;

export function GetDownloads():Promise<map[string]main.AppDownload>;

export function GetOwnedGames():Promise<Array<main.AppGame>>;

export function IsDownloading(arg1:string):Promise<number>;

export function StartDownloadListener():Promise<void>;

export function UploadGame(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number):Promise<string>;
