// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {games} from '../models';

export function GetOwnedGames():Promise<Array<games.Game>>;

export function Greet(arg1:string):Promise<string>;
