// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeployLibraryInstance(arg1) {
  return window['go']['main']['App']['DeployLibraryInstance'](arg1);
}

export function GetOwnedGames() {
  return window['go']['main']['App']['GetOwnedGames']();
}

export function UploadGame(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadGame'](arg1, arg2, arg3, arg4, arg5, arg6);
}
