// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDownload(arg1) {
  return window['go']['main']['App']['CreateDownload'](arg1);
}

export function DeployLibraryInstance(arg1) {
  return window['go']['main']['App']['DeployLibraryInstance'](arg1);
}

export function GetAllGames() {
  return window['go']['main']['App']['GetAllGames']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetOwnedGames() {
  return window['go']['main']['App']['GetOwnedGames']();
}

export function IsDownloading(arg1) {
  return window['go']['main']['App']['IsDownloading'](arg1);
}

export function StartDownloadListener() {
  return window['go']['main']['App']['StartDownloadListener']();
}

export function UploadGame(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UploadGame'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
