
fetch-data-lin:
	wget https://github.com/t02smith/latex-template/archive/main.tar.gz
	tar -xzvf main.tar.gz
	rm main.tar.gz

# \
curl -o main.zip https://github.com/t02smith/latex-template/archive/main.zip \
Expand-Archive main.zip  \
mv .\main\latex-template-main . \
rm .\main.zip \
rm .\main

# ^ run this for windows
#   stupid powershell smh

	