contract:
    address: 0x2899Dab55A4A20D698062bBF4d4ce9f1073Ce052
eth:
    address: https://eth-sepolia.g.alchemy.com/v2/v51CbZclQLLclPgsqRwBINAYtA76FHAs
games:
    installfolder: ./downloads
meta:
    directory: .toolkit
    hashes:
        shardsize: 16384
        workercount: 5
    log: stdout
net:
    peer:
        continuedownloads: true
        max_connections: 100
        serve_assets: true
        serveassets: true
        skip_validation: false
        skipvalidation: false
        use_known_peers: false
    port: 6052
user:
    info:
        name: ""
