eth:
    address: ws://localhost:8545
games:
    installfolder: ./test/data/tmp
meta:
    directory: ./test/data/.toolkit
    hashes:
        shardsize: 16384
        workercount: 5
    log: stdout
    threadpoolsize: 10
net:
    "\0\0\0\0\0\0\0\0peers": false
    port: 6749
    useknownpeers: false
user:
    info:
        domain: t02smith.com
        name: tom
