contract:
    address: 0x750cf6392175f94ff5014803a0bb6b79de543337
eth:
    address: http://localhost:8545
games:
    installfolder: ./test/data/tmp
meta:
    directory: ./test/data/.toolkit
    hashes:
        shardsize: 16384
        workercount: 5
    log: stdout
net:
    peer:
        continuedownloads: true
        dovalidation: true
        serveassets: true
        useknownpeers: false
    port: 6749
user:
    info:
        name: ""
